name 'simpleNasBox'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures simpleNasBox'
long_description 'Installs/Configures simpleNasBox'
version '0.1.0'
